name: CI/CD for limestone-chat staging

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  GO_VERSION: '1.24.3'
  APP_NAME: limestone-chat
  DOCKER_IMAGE_NAME: limestone-chat
  DIGITALOCEAN_REGISTRY: registry.digitalocean.com/limestone-image

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }} # Menggunakan variabel env
          cache: false

      - name: Download Go modules
        run: go mod download

      - name: Run Go unit tests
        run: go test ./test/... -v

  build:
    name: Build
    needs: tests
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DIGITALOCEAN_REGISTRY }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DIGITALOCEAN_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:v1.0.0
            ${{ env.DIGITALOCEAN_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          file: ./Dockerfile

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prepare .env content for Droplet
        id: env_content
        run: |
          # Perbaiki penulisan >> untuk setiap baris
          ENV_VARS_RAW=$(echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
          echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}"
          echo "REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}"
          echo "ACCESS_EXPIRATION=${{ secrets.ACCESS_EXPIRATION }}"
          echo "REFRESH_EXPIRATION=${{ secrets.REFRESH_EXPIRATION }}"
          )
          echo "ENV_FILE_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$ENV_VARS_RAW" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Deploy Docker Image to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login ${{ env.DIGITALOCEAN_REGISTRY }} --username ${{ secrets.DIGITALOCEAN_USERNAME }} --password-stdin

            IMAGE_TAG="${{ env.DIGITALOCEAN_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:v1.0.0"
            CONTAINER_NAME="${{ env.APP_NAME }}"

            echo "Checking for existing container ${CONTAINER_NAME}..."
            if docker ps -a --format '{{.Names}}' | grep -q "${CONTAINER_NAME}"; then
              echo "Stopping existing container ${CONTAINER_NAME}..."
              docker stop "${CONTAINER_NAME}" || true
              echo "Removing existing container ${CONTAINER_NAME}..."
              docker rm "${CONTAINER_NAME}" || true
            else
              echo "No existing container ${CONTAINER_NAME} found."
            fi

            echo "Pulling Docker image: ${IMAGE_TAG}..."
            docker pull "${IMAGE_TAG}"

            echo "Creating .env file on Droplet at /tmp/.env..."
            # Pastikan Anda menggunakan 'EOF_ENV' sebagai delimiter, tidak 'EOF' jika ada variabel lain
            cat << 'EOF_ENV' > /tmp/.env
            ${{ steps.env_content.outputs.ENV_FILE_CONTENT }}
            EOF_ENV
            
            echo "Running new container ${CONTAINER_NAME}..."
            docker run -d \
              --name "${CONTAINER_NAME}" \
              --restart unless-stopped \
              --env-file /tmp/.env \
              -p 8082:8082 \
              "${IMAGE_TAG}"

            rm /tmp/.env

            echo "Deployment to Droplet complete!"